nginx.org/server-snippets: |
    resolver kube-dns.kube-system valid=10s;
    location = /mirror {
        internal;
        set $shadow_service_name {{service}};
        proxy_set_header X-Mirror-Request  true;
        proxy_set_header X-Shadow-Service  $shadow_service_name;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header Host  $host;
        proxy_pass http://{{mirror}}.{{namespace}}.svc.cluster.local$request_uri;
    }
nginx.org/location-snippets: |
    mirror  /mirror;
