apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-controller
spec:
  backoffLimit: 4
  activeDeadlineSeconds: 100
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: k8s-controller
        image: galonedocker/k8s:controller
      restartPolicy: Never
